### ISSUE TITLE
Intangible/Base Metals incompatibility

### ISSUE THREAD

**Issue by Aaronmessina** [Resonant-Rise/ResonantRiseV4#10]
###### Mod In Question

> Base metals
###### Expected behavior

> Villagers are one of two ways to get wise souls, witches being the second way. When base metals is installed, the villagers are replaced with "better villagers" making them incompatible with intangible soul extracting, making getting wise souls extremely tedious  
###### Suggestion on how to fix or supply fix

>  Disable villager modifications in the Base Metals config, or contact mod authors

**Comment by Ryahn** [comment]
This is been done as of 3 days ago.
