### ISSUE TITLE
In case of emergency death by drowning

### ISSUE THREAD

**Issue by KendirkRS** [Resonant-Rise/ResonantRiseV4#13]
Mod In Question
In Case of Emergency

deaths in water voids items by becoming blocks
###### Expected behavior

Die and your head will appear to collect item
###### Actual Behavior

items appear in an purple and black box that can't reclaim items from
###### Steps to reproduce

Just drown in water

**Comment by KendirkRS** [comment]
![2016-02-27_15 45 40](https://cloud.githubusercontent.com/assets/17441461/13373805/547f9650-dd26-11e5-9c2f-c57a20698c01.png)
![2016-02-27_15 45 19](https://cloud.githubusercontent.com/assets/17441461/13373806/548256f6-dd26-11e5-9329-f521c0d619bd.png)

**Comment by macserv** [comment]
We've had another instance of this.  The block is an `ice:deathmarker`.

**Comment by Ryahn** [comment]
Hopefully fixed in Pre-Release [Alpha-0.2.0](https://github.com/Resonant-Rise/ResonantRiseV4/commit/f173921e6314292c8f3d4e7c1a94283e23f63f7e)

Replaced with GraveStone
