### ISSUE TITLE
Crash with Rod of the Terra Firma

### ISSUE THREAD

**Issue by Dr-Excalibur** [Resonant-Rise/ResonantRiseV4#14]
###### Mod In Question

> Botania
###### Link to crash log

> http://paste.resonant-rise.com:7777/agaculewid.coffee
###### Expected behavior

> When using the Rod of the Terra Firma, the earth beneath you is shaped according to the Y-level you are standing on
###### Actual Behavior

> Instant crash
###### Steps to reproduce

> Just use it. I used it standing in water, if that helps
###### Suggestion on how to fix or supply fix

> Inform Willie

**Comment by Ryahn** [comment]
Fixed in an update https://github.com/williewillus/Botania/issues/138

Will be fixed in next pack update
