### ISSUE TITLE
Add Mod Realistic Terrain Generation for Testing.

### ISSUE THREAD

**Issue by Esriel123** [Resonant-Rise/ResonantRiseV4#15]
###### Mod In Question

> Realistic Terrain Generation
###### Link to Mod

> http://minecraft.curseforge.com/projects/realistic-terrain-generation
###### Expected behavior

> Add very good Looking Terrain. 
###### Actual Behavior

> ## 
###### Steps to reproduce

> Add Mod ;)
###### Suggestion on how to fix or supply fix

> It would be awesome if we could add the Mod for Testing.

**Comment by Esriel123** [comment]
And along with that for the Real Feels: http://minecraft.curseforge.com/projects/stellar-sky

**Comment by GodNero** [comment]
Es... this is for issues no mod requests.

**Comment by GodNero** [comment]
nero is a derp....

**Comment by Ryahn** [comment]
Added in Pre-Release [Alpha-0.2.0](https://github.com/Resonant-Rise/ResonantRiseV4/commit/f173921e6314292c8f3d4e7c1a94283e23f63f7e)
