### ISSUE TITLE
Matter overdrive and Magneticraft [suggestion]

### ISSUE THREAD

**Issue by ghost** [Resonant-Rise/ResonantRiseV4#16]
Since rr will soon require Java 8 to run i fan finnaly make theses suggestions for the pack... 
Matter overdrive is a mod about sci-fi star trek and a taste of future , it adds Matter Duplication , Android capabilities and new awseome weapons,
my second suggestions , is magneticraft , a mod thats like a bit more factorio feeling able to do processing with robot arms and conveyer belts, it adds about x4 and more ore duplication with multiblock machines. It also adds some other bits and bops.

**Comment by ghost** [comment]
Oh also another suggestion would be academycraft or ars magica 
Academycraft adds wireless power , the machine can act like a really good IE wire relay, academycraft Also adds player infusion which is randomly chosen by the game , all of the three infusions give you different powers.
Then ars magica 2, we pretty much know What it does

**Comment by Ryahn** [comment]
We will be waiting to add these. Need to test a few prior mods to see if they are fixed

**Comment by Esriel123** [comment]
these Mods are on MC 1.7.9 RR4 is 1.8.9 Testpack.

**Comment by ghost** [comment]
Matter overdrive is on 1.8.9 too.

**Comment by misterfixit** [comment]
Matter Overdrive will be considered for the 1.9 pack but it won't be added to the 1.8.9 because focus is being moved to 1.9
