### ISSUE TITLE
Tree grows rftools chambers

### ISSUE THREAD

**Issue by ghost** [Resonant-Rise/ResonantRiseV4#18]
###### Mod In Question

> Rftools and tree growing

 http://i.imgur.com/TZ4Bum1.png
###### Steps to reproduce

> grow trees

**Comment by Ryahn** [comment]
Reported
https://github.com/McJty/RFTools/issues/465

**Comment by Ryahn** [comment]
Not an RFTools bug. Issue with either server, client or just a random mishap.
