### ISSUE TITLE
Conflict while trying to craft slab

### ISSUE THREAD

**Issue by Clem105** [Resonant-Rise/ResonantRiseV4#20]
###### Mod In Question

> MC vanilla and a mod changing stone slab craft
###### Link to crash log

> http://pastebin.com/SweZxNYt
###### What Happend ?

> Instead of being able to craft normal stone slab, I see 1/2 stoned textured slab and when I try to craft it , is crash ( tried 3 times ) .
###### Steps to reproduce

> Try to craft stone slab in normal crafting table
> ###### Suggestion on how to fix or supply fix
> 
> May just diseable the concerned stone textured slab block

**Comment by KendirkRS** [comment]
want to inform theres quite a few that crashes when trying to make slabs or stairs like normal stones and others but i need to redo my list will update when i can
