### ISSUE TITLE
Add Soul Shards:The Old Ways

### ISSUE THREAD

**Issue by Esriel123** [Resonant-Rise/ResonantRiseV4#21]
###### Mod In Question

> Soul Shards: The Old Ways
###### Link to crash log

> http://minecraft.curseforge.com/projects/soul-shards-the-old-ways
###### Expected behavior

> Spawn Mobs on a tier-Based Spawner with highly configurable Configs
###### Actual Behavior

> In the Config Folder of the Mod, there is a .json, where you can configure everything about the tiers. 
> @mister_fix_it, also Redstone works on all Tiers if so configured!!!
###### Steps to reproduce

> ## 
###### Suggestion on how to fix or supply fix

> ##

**Comment by Ryahn** [comment]
Will have to let fixit see this

**Comment by Ryahn** [comment]
Added in Pre-Release [Alpha-0.2.0](https://github.com/Resonant-Rise/ResonantRiseV4/commit/f173921e6314292c8f3d4e7c1a94283e23f63f7e)
