### ISSUE TITLE
NPC's FPS hit unable to talk to or kill

### ISSUE THREAD

**Issue by KendirkRS** [Resonant-Rise/ResonantRiseV4#22]
###### Mod In Question

Current mod that NPC's are assigned to
###### Expected behavior

option to trade even kill if wanted
normal FPS
###### Actual Behavior

no crash but severe FPS hit can't talk to them or kill them
###### Steps to reproduce

Just entering a town
###### Suggestion on how to fix or supply fix

disable npcs or current mod npc

**Comment by mikuhl-dev** [comment]
Getting extreme FPS drops near villages also.
