### ISSUE TITLE
Crafting Slabs Furnace

### ISSUE THREAD

**Issue by KendirkRS** [Resonant-Rise/ResonantRiseV4#26]
###### Mod In Question

Crafting Slabs
###### Link to crash log

No Crash
###### Expected behavior

use Pickaxe or hand to remove item and pick it up
###### Actual Behavior

Pickaxes one click the item up, no pickaxes = creative mode and distory's item and 2 stacked together won't dissappear and dupe it
###### Steps to reproduce

place one on floor left click with empty hand and disappears left click with pickaxes it single clicks and picks up stack one on the other it it joins to make a full looking furnace but can't be destroyed
###### Suggestion on how to fix or supply fix

no suggestion 
![2016-03-14_18 13 35](https://cloud.githubusercontent.com/assets/17441461/13755075/7293cb46-ea11-11e5-958f-e4f1595f80d0.png)
![2016-03-14_18 13 24](https://cloud.githubusercontent.com/assets/17441461/13755076/72942c12-ea11-11e5-8a2b-d7d8e2c6e7ff.png)

**Comment by Lanse505** [comment]
Mod is getting dropped
