### ISSUE TITLE
Grave stones not appearing

### ISSUE THREAD

**Issue by KendirkRS** [Resonant-Rise/ResonantRiseV4#27]
###### Mod In Question

Gravestones
###### Link to crash log

--none
###### Expected behavior

random type of gravestone to appear on death
###### Actual Behavior

nothing appears and items go missing
###### Steps to reproduce

... die....
###### Suggestion on how to fix or supply fix

.....

**Comment by Clem105** [comment]
Happend to me too , as far as I tested it seems to be 100% of the time
