### ISSUE TITLE
Crashing while launching a game

### ISSUE THREAD

**Issue by Clem105** [Resonant-Rise/ResonantRiseV4#28]
###### Mod In Question

> Launcher 
###### Link to crash log

> http://pastebin.com/N9vjzVMQ
###### Expected behavior

> Opening a new map should create it and you open her
###### Actual Behavior

> Send you back to main menu
###### Steps to reproduce

> Try to create a new map

**Comment by StrayCargo** [comment]
@Clem105 Can you please post the full crash log

**Comment by Lanse505** [comment]
I'm gonna close this issue since RR has moved onto 1.9 and this issue isnt happening.
