### ISSUE TITLE
Integrated dynamics Failure to out put liquids

### ISSUE THREAD

**Issue by StrayCargo** [Resonant-Rise/ResonantRiseV4#31]
###### Mod In Question

> Integrated Dynamics 
###### Link to crash log

> No Crash Log Available 
> ![2016-04-24_20 29 32](https://cloud.githubusercontent.com/assets/8396060/14771860/e1129ee8-0a5b-11e6-8c13-535b4b9f1af7.png)
###### Expected behavior

> Liquids to come out of item as output
###### Actual Behavior

> No items coming out at all
###### Steps to reproduce

> 1. Take squeezer put a Menril Log inside with right click and jump on squeezer also you can put a tank of any mod next to it to have liquid output go into it from the squeezer
###### Suggestion on how to fix or supply fix

> Not really sure

**Comment by Lanse505** [comment]
have this been tested against the 1.9 build?

**Comment by misterfixit** [comment]
The issue persists, however instead of nothing it produces mithril dust. The recipe for mithril dust is nothing in a squeezer so i imagine it overrides all other recipes

**Comment by xXXStrykerXXx** [comment]
I can second this issue if that makes any difference. Do we know if the mod is to blame or crafting/recipe conflicts?

**Comment by StrayCargo** [comment]
It would appear then that there are in fact some recipe conflicts with this mod I suggest we take a look at a reinstall of the mod @Lanse505 @misterfixit to try and resolve the issue if that doesn't work perhaps contact the mod author or try to look into the file for that mod and see whats causing the conflict or override

**Comment by misterfixit** [comment]
A reinstall of the mod wouldnt do any good ill submit a but report to the author later today

**Comment by StrayCargo** [comment]
ok thanks on that not a I will close the issue and leave the note that the author has been notified
