### ISSUE TITLE
Gravestone deleting items

### ISSUE THREAD

**Issue by KendirkRS** [Resonant-Rise/ResonantRiseV4#33]
###### Mod In Question

Graves Mod
###### Link to crash log

No crash
###### Expected behavior

to produce a grave and stone where you died
###### Actual Behavior

it produced everything ok but as seen in picture where the stone is was a furnace and it deleted it
###### Steps to reproduce

not easy to reproduce 
but envoles dying dear items
###### Suggestion on how to fix or supply fix

.....
![2016-05-03_19 52 15](https://cloud.githubusercontent.com/assets/17441461/14994694/317b3f3e-1169-11e6-9646-129189fa90c5.png)

**Comment by Lanse505** [comment]
I can't reproduce this issue in-game :/ is this 1.8.9 or 1.9?

**Comment by KendirkRS** [comment]
1.9 its hard to reproduce as it is specific

**Comment by StrayCargo** [comment]
No way to fix mod issue not pack issue

**Comment by StrayCargo** [comment]
Ticket close
