### ISSUE TITLE
Dimensional Anchors Bug

### ISSUE THREAD

**Issue by xXXStrykerXXx** [Resonant-Rise/ResonantRiseV4#34]
###### Mod In Question

> Dimensional Anchors
###### Link to crash log

> No access to server crash logs
###### Expected behavior

> Break block and the item return to inventory
###### Actual Behavior

> When you break a chunk loader, it disappears in the visual sense. However, when you try to walk where the block was, it repulses you as if it were still there. When you place a new block where the chunk loader was, the chunk loader reappears. There are two issues. One, you cannot break the chunk loader. Two, when trying to use a block breaker to break the chunk loader, the server crashes.
###### Steps to reproduce

> Craft a chunk loader. Place said chunk loader in the world. 1.) Attempt to break the chunk loader. 2.) Break chunk loader with a block breaker.
###### Suggestion on how to fix or supply fix

> Unsure other than removing the mod or waiting for an update

**Comment by StrayCargo** [comment]
Mod update required to fix this issue
