### ISSUE TITLE
[Easily Fixable Issue] - OreGen 1.9 Pack

### ISSUE THREAD

**Issue by Lanse505** [Resonant-Rise/ResonantRiseV4#35]
###### Mod In Question

BaseMetals, Substratum, RoutersReborn, ModernMetals (BM Addon)
###### Expected behavior

Only Base Metal Copper/Tin/Silver/Lead should spawn. 
However i've thus found both Substratum and RoutersReborn to spawn their Copper variants,
Substratum also spawns it's tin, silver, lead, nickel, zinc. 

ModernMetals:
The following metals needs to be turned off;
Chromium
Iridium
Plutonium
Titanium
Tungsten
Uranium
Zirconium

Otherwise we break TechReborn and IC2 Progression (when Ic2 drops).

**Comment by xXXStrykerXXx** [comment]
I would add to this by saying that there are a ton of duplicate ores. From copper, tin, and lead to Biomes O' Plenty rubies and TechReborn rubies. I get it though, the pack's new.

**Comment by Lanse505** [comment]
TechReborn ores are enabled until i can take a good look at what can and can not be disabled (BoP Gems can be disabled though yes)

**Comment by Lanse505** [comment]
I don't want to fuck-up TR by removing needed mod ores.
