### ISSUE TITLE
Blood Magic Rudimentary Snare

### ISSUE THREAD

**Issue by Dr-Excalibur** [Resonant-Rise/ResonantRiseV4#36]
###### Mod In Question

> Blood Magic
###### Link to crash log

> N/A
###### Expected behavior

> When a rudimentary snare is thrown at a mob, there is a chance it will apply a 15 second status effect on the affected mob. When killed, the mob is guarenteed to drop an item named "Demonic Will", which is required to begin the early game Blood Magic
###### Actual Behavior

> The effect is applied randomly, however, when the mob dies with the effect, the will doesn't drop
###### Steps to reproduce

> Throw snares at a mob until white particle effects float around it. Then kill the mob.
###### Suggestion on how to fix or supply fix

> Notify Way

**Comment by Dr-Excalibur** [comment]
For some reason, the Sentient Sword, an item that applies the same status effect, does drop the Will

**Comment by StrayCargo** [comment]
Checked issue and found not an issue or bug seems to work just fine

**Comment by StrayCargo** [comment]
Issue can be closed
