### ISSUE TITLE
Issue with Ranged Collector

### ISSUE THREAD

**Issue by xXXStrykerXXx** [Resonant-Rise/ResonantRiseV4#37]
###### Mod In Question

> Actually Additions and QuantumFlux
###### Link to crash log

> N/a
###### Expected behavior

> The Ranged Collector should pick up blocks within a vicinity around it; additionally it should pick up items before they enter your inventory.
###### Actual Behavior

> It is performing it's function, but while having the Item Magnet from QuantumFlux active the Ranged Collector will gather an item on the ground, but so will the Item Magnet. It essentially duplicates the item every time.
###### Steps to reproduce

> Place a Ranged Collector, then activate your Item Magnet. Throw an item(s) from your inventory onto the ground. You'll notice the item get sucked back into your inventory and an exact copy of said item in the Ranged Collector.
###### Suggestion on how to fix or supply fix

> Unsure, but I'm guessing it's some kind of prioritizing conflict. I think that the Ranged Collector is instantly warping the item into it's inventory, instead of actually "drawing" the item into it. The Item Magnet also acts instantaneously, so therein lies the issue. It's a really nasty dupe glitch too, because it works on stacks of items as well.

**Comment by StrayCargo** [comment]
This sounds like either a mod update issue or a config conflict
