### ISSUE TITLE
Issue with TechReborn Generator

### ISSUE THREAD

**Issue by xXXStrykerXXx** [Resonant-Rise/ResonantRiseV4#38]
###### Mod In Question

> TechReborn
> ###### Link to crash log
> 
> N/a
###### Expected behavior

> When wrenching a TR Generator, you'd expect for the items to drop out of the Generator once it was broken.
###### Actual Behavior

> The items drop out, but whatever was inside of the Generator when broke is duplicated.
###### Steps to reproduce

> Place a Generator down, place a piece or a stack of fuel (coal, coal blocks, etc.) inside of the Generator, and then shift right-click on it with a wrench.
###### Suggestion on how to fix or supply fix

> Unsure, the mod is still in alpha so there are bound to be some bugs.

**Comment by Lanse505** [comment]
First we need to check if it's been fixed in a newer update. 
Secondly @xXXStrykerXXx Could you do a quick check if this issue has been reported on their github?
Thirdly Yes it's still "technically" in alpha so bugs are bound to happen.

**Comment by xXXStrykerXXx** [comment]
I can't seem to find it in their open issues at least. They have a lot of closed issues as well but I couldn't see it when I looked through them either. I thought it may be an issue with the item magnet from QuantumFlux, but the duplication happened with it on or off.

**Comment by ghost** [comment]
This is 1.9 correct ?

**Comment by Lanse505** [comment]
@Alexismachina This is 1.9 indeed

**Comment by Lanse505** [comment]
We're gonna test against the newest update
