### ISSUE TITLE
Tech Reborn infinite energy issue

### ISSUE THREAD

**Issue by wagon153** [Resonant-Rise/ResonantRiseV4#40]
###### Mod In Question

Tech Reborn
###### Link to crash log

No crash log here, just a bug
###### Expected behavior

For the grinder's internal buffer to empty and cause the machine to slow down considerably
###### Actual Behavior

The grinder somehow magically retains it's energy buffer, despite the battery box's buffer being emptied.
###### Steps to reproduce

Well, here's a screenshot of my setup. Generator next to the batbox, which has a insulated copper cable underneath it running into my grinder and extractor.

[2016-05-26_19 21 28](https://cloud.githubusercontent.com/assets/6232096/15593100/382515ba-2377-11e6-966b-f38f83cf0902.png)

Speaking of which, this issue appears to also exist for other machines, as it also happens with my extractor and Electric Furnace.
###### Suggestion on how to fix or supply fix

Can't say I know enough to provide one unfortunately.

**Comment by Lanse505** [comment]
This issue should be fixed in 1.9.4!
I've opened up a better channel of communication with the TR Devs so if this issue is still "present" in 1.9.4 then i'll push this directly up the chain cause it seems to be large scale issue!
