### ISSUE TITLE
minecraft bug

### ISSUE THREAD

**Issue by bird191** [Resonant-Rise/ResonantRiseV4#42]
###### Mod In Question

> minecraft
###### Link to crash log

> Type here
###### Expected behavior

> nether portal in nether should be linked to my nether portal overworld
> ###### Actual Behavior
> 
> it instead is sending me to someone else's base 1000 blocks away
###### Steps to reproduce

> Type here
###### Suggestion on how to fix or supply fix

> see if there is a mod that fixes minecraft nether portal bugs

**Comment by Lanse505** [comment]
Will be fixed next update with "NetherPortalFix"
