### ISSUE TITLE
Minecart with chest bug (balance issue related)

### ISSUE THREAD

**Issue by Chris-Paquette** [Resonant-Rise/ResonantRiseV4#44]
###### Mod In Question

> Forge?
###### Link to crash log

> No crash, just a balance issue
###### Expected behavior

> Find minecart with chest #0342. Open chest, remove items, chest remains empty until it is filled by the player.
###### Actual Behavior

> Chest is refilled upon closing out of the gui, and refilled with new items pulled from the loot table. This is repeatable indefinitely.
###### Steps to reproduce

> Either find a minecart with chest #0342 or craft one, left click to open said chest pull items (or don't, doesn't affect it). Close the chest, then re-open.
###### Suggestion on how to fix or supply fix

> Type here

**Comment by Lanse505** [comment]
Hmm not a forge issue, seems to be a mod issue? 
@misterfixit @GodNero @Ryahn Something to Investigate! 
(Mod by Mod run again :D)

**Comment by Lanse505** [comment]
Fixed in 1.9.4!
