### ISSUE TITLE
Storage Drawers rendering crash

### ISSUE THREAD

**Issue by Dr-Excalibur** [Resonant-Rise/ResonantRiseV4#48]
###### Mod In Question

> Storage Drawers
###### Link to crash log

> http://pastebin.com/LqL5R6KU
###### Expected behavior

> Drawer renders item(s) stored in it
###### Actual Behavior

> Instant return to ATL if chunk with drawer is loaded
###### Steps to reproduce

> Go to Nero's base
###### Suggestion on how to fix or supply fix

> Remove the drawer

**Comment by Lanse505** [comment]
Fixed in 1.9.4
