### ISSUE TITLE
Tessellating Block Model

### ISSUE THREAD

**Issue by D-Sneki** [Resonant-Rise/ResonantRiseV4#49]
###### Mod In Question

> Storage Drawers and/or Tinker's Construct
###### Link to crash log

> http://pastebin.com/VnNRvcNd
###### Expected behavior

> Placing Oak Drawer 1x2 in Crafting Station
###### Actual Behavior

> Crash upon entering server
###### Steps to reproduce

> Craft a Drawer Upgrade Template
###### Suggestion on how to fix or supply fix

> ???

**Comment by mikuhl-dev** [comment]
I'm receiving this also by going near an area in a random forest.

**Comment by Lanse505** [comment]
Fixed in 1.9.4
