### ISSUE TITLE
CHESTCART DUPE

### ISSUE THREAD

**Issue by pommie001** [Resonant-Rise/ResonantRiseV4#50]
###### Mod In Question

Vanilla / RRM V4 test
###### Link to crash log

no crash
###### Actual Behavior

when opening a minecart on a piece of track it acts like a mineshaft (minecart). 
you can also keep closing and opening to respawn new loot.
u can also just craft a chest and cart and make it a chestcart place it on track and it turns into a mineshaft Chestcart you can loot over and over..
###### Steps to reproduce

just make a chestcart and place on track anywhere in world
###### Suggestion on how to fix or supply fix

> Type here

**Comment by Lanse505** [comment]
Already Documented, Should be fixed in 1.9.4.
We have no clear cut explaination what's causing this in 1.9

**Comment by Lanse505** [comment]
Yea this is fixed in 1.9.4!

Hopefully you'll get access to the 1.9.4 build within a week at most.
Currently going through alot of Oregen Revision and things that's gonna require World Resets if you get the build now, so I'm holding off on it for now.
