### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by bird191** [Resonant-Rise/ResonantRiseV4#51]
i came out of the nether where neros base is and now my minecraft crashes everytime i log in

**Comment by Lanse505** [comment]
We're aware of the crash.
Give your information to @misterfixit in a PM on Slack and he'll get you moved.

Hopefully i'll have a 1.9.4 release ready for you testers within a Week (No Promises)

**Comment by bird191** [comment]
i sent it to him in a repository on github. that should work right?

**Comment by bird191** [comment]
lanse i need your help i cant get into slack so i poked fix it on teamspeak
since i couldnt talk to him on slack and he banned me from teamspeak. If i
pissed him off i didnt mean to but he caused a problem which basically
screwed my character on the server. i need to get de banned please. i am
sorry if i did tick him off

**Comment by misterfixit** [comment]
Bird you have been removed from the testers, I don't think you can handle being on a test server. Especially when you blame the person trying to help you.
