### ISSUE TITLE
Ore Generation Duplicates

### ISSUE THREAD

**Issue by xXXStrykerXXx** [Resonant-Rise/ResonantRiseV4#56]
###### Mod In Question

> Substratum, Forestry
###### Link to crash log

> N/a
###### Expected behavior

> Having only one type of individual ores underground.
###### Actual Behavior

> There are multiple of the same ores underground.
###### Steps to reproduce

> Generate a world.
###### Suggestion on how to fix or supply fix

> Change the configs before next world reset.

**Comment by misterfixit** [comment]
Those were fixed last update it's just those chunks were already generated, any new chunks should only have substratum ores
