### ISSUE TITLE
Make BetterMinecraftChat optional (or remove it)

### ISSUE THREAD

**Issue by KaiKikuchi** [Resonant-Rise/ResonantRiseV4#58]
###### Mod In Question

> BetterMinecraftChat

Can you consider to move this mod to optional at least..?

It has a lot of issues with random emoticons.

Also there is a bad issue with new lines in messages that cause the message to not appear at all.

This means that all Sponge mods that use new lines in messages will have issues (messages not showing in chat). Link to issue: https://github.com/blay09/BetterMinecraftChat/issues/26

Because of this issue, we are just removing it from our clients.

**Comment by misterfixit** [comment]
https://github.com/Resonant-Rise/ResonantRiseV4/commit/564e822bb8d971f744e6189c5d9a55aa771c0ffc

Moved to optional
