### ISSUE TITLE
[1.10 Branch] Mod Addition Request - Iron Backpacks

### ISSUE THREAD

**Issue by gr8pefish** [Resonant-Rise/ResonantRiseV4#59]
Hello,

Apoligies in advance that this isn't the best place to put this, I simply didn't know where else to post it so that it was not simply ignored in the flood of other messages.

Anyways, recently I have been [very hard at work](https://github.com/gr8pefish/IronBackpacks/graphs/contributors?from=2016-09-10&to=2016-10-06&type=c) on my mod, [Iron Backpacks](https://minecraft.curseforge.com/projects/iron-backpacks), improving it immensely and I think it would be a fantastic addition to Resonant Rise for MC 1.10. I strongly urge you in considering its inclusion in the latest version of the pack.

If you accept, I can also create a pull request to modify the xml files and anything else that is needed actually add the mod, so that all you have to do is click the "Merge PR" button. 

I'm super active (see that 1st link for proof haha), so if you have any questions/comments/etc. just let me know and I'd be happy to respond.

Thank You!

**Comment by misterfixit** [comment]
I will take a look at the mod later today, just curious does this have any dependency on iron chests?

**Comment by gr8pefish** [comment]
Thanks. No, no dependencies (although it does have some mod integration, nothing is required).

**Comment by misterfixit** [comment]
Good i didnt plan on adding iron chests this go around, plenty of other chest options anyway

**Comment by misterfixit** [comment]
Iron backpacks has been added to the dev branch

**Comment by gr8pefish** [comment]
Sweet! If you have any questions/comments/suggestions/bug reports/etc, just post something on my [Issue Tracker](https://github.com/gr8pefish/IronBackpacks/issues) and I'll try to get back to you ASAP.

**Comment by misterfixit** [comment]
Will do, appreciate you posting in the first place, probably wouldn't have seen it otherwise

**Comment by gr8pefish** [comment]
No problem :) I'm going to push out a decently sized update pretty soon here (hopefully by the end of next week), with texture remodeling, recipe changes, and a big bugfix/change to how equipped backpacks are stored internally, just as a heads up.

Edit: Reworded for clarity.
