### ISSUE TITLE
InfiniApple Server Crash

### ISSUE THREAD

**Issue by Dr-Excalibur** [Resonant-Rise/ResonantRiseV4#6]
###### Mod In Question

> CrissCross
###### Link to crash log

> https://a.pomf.cat/zcoosf.txt
###### Expected behavior

> Constant refill of hunger
###### Actual Behavior

> Server Crash
###### Steps to reproduce

> Have InfiniApple in inventory
###### Suggestion on how to fix or supply fix

> Disable the InfiniApple temporarily until the mod dev issues a fix for it

**Comment by GodNero** [comment]
The mod developer was informed of this issue, prior to us having the issue, waiting on update fix.
