### ISSUE TITLE
[1.10 Branch] [Suggestion] Vazkii's new mods

### ISSUE THREAD

**Issue by SamKemp** [Resonant-Rise/ResonantRiseV4#60]
`I'm not sure if this is the correct place for this so feel free to move it/ask me to move it.`

I beleive that Vazkii's new mods [Morph-o-Tool](https://minecraft.curseforge.com/projects/morph-o-tool) and [Akashic Tome](https://minecraft.curseforge.com/projects/akashic-tome) would be useful aditions to the pack.

They both have the requirement of [AutoRegLib](https://minecraft.curseforge.com/projects/autoreglib)

Mod showcase for both can be seen here:
[![DireWolf20 --> Mod Spotlights - Morph O Tool and Akashic Tome ](https://img.youtube.com/vi/474zXsRHJIQ/0.jpg)](https://www.youtube.com/watch?v=474zXsRHJIQ)

**Comment by misterfixit** [comment]
Morph o tool is currently there, the time mod I haven't had a chance to look at fully yet, but I will defenitely check it out

**Comment by misterfixit** [comment]
Akahsic tone has been added to the dev pack
