### ISSUE TITLE
Super circuit maker recipe conflict

### ISSUE THREAD

**Issue by ghost** [Resonant-Rise/ResonantRiseV4#67]
###### Mod In Question
> Super Circuit Maker, Substratum

###### Expected behavior
> Tiny Pile of Redstone should have been crafted

###### Actual Behavior
> Recipe conflict with Substratum's small pile of redstone

###### Steps to reproduce
> Place redstone in crafting grid

###### Suggestion on how to fix or supply fix
> Minetweaker

**Comment by GodNero** [comment]
Mod substratum that was causing the issue has been removed, opted to use new system for handling ores so this should not longer be an issue.
