### ISSUE TITLE
Mod Requests as Discussed with Nero

### ISSUE THREAD

**Issue by Lanse505** [Resonant-Rise/ResonantRiseV4#68]
###### Mod In Question:
Mod Name Tooltip:
https://minecraft.curseforge.com/projects/mod-name-tooltip?gameCategorySlug=mc-mods&projectID=238747

Client Tweaks:
https://minecraft.curseforge.com/projects/client-tweaks?gameCategorySlug=mc-mods&projectID=251407

Steve's Factory Manager:
https://minecraft.curseforge.com/projects/steves-factory-manager-reborn?gameCategorySlug=mc-mods&projectID=253338

Steve's Carts 2:
https://minecraft.curseforge.com/projects/steves-carts-reborn?gameCategorySlug=mc-mods&projectID=253462

Natura:
https://minecraft.curseforge.com/projects/natura

Funky Locomotion:
https://minecraft.curseforge.com/projects/funky-locomotion

Remove Applecore:
AppleSkin does the Saturation Overlay also but without unneeded code.
(Approved by Nero)

NEI (Since when installed with JEI it's just a Addon that adds the buttons, dump tools, subsets, etc)
https://minecraft.curseforge.com/projects/not-enough-items-1-8?gameCategorySlug=mc-mods&projectID=247694

Ore Excavation Instead of Veinminer:
It is:
   - More Lightweight
   - Less Crashprone 
   - Has a more active dev
   - Gives us more configurability in what and how it operates.
https://minecraft.curseforge.com/projects/ore-excavation

More Bees:
https://minecraft.curseforge.com/projects/more-bees

MFFS:
https://minecraft.curseforge.com/projects/modular-forcefield-system

OpenEye:
https://minecraft.curseforge.com/projects/openeye

Ambidextrous:
https://minecraft.curseforge.com/projects/ambidextrous

Initial Inventory (By Jared) - Used if we choose to implement a starting inventory
https://minecraft.curseforge.com/projects/initial-inventory
(Example: 16 torches 8 apples, Stone Sword, Akachi Tome with All the needed Books)

**Comment by Lanse505** [comment]
Update all the Mods

**Comment by Lanse505** [comment]
Update Mekanism since it fixes the Cable Crash

**Comment by GodNero** [comment]
warning when updating storage drawers against current build - 3.5.0 or 3.5.1 causing an odd crash I haven't locked down the cause of yet. 
3.4.4 will work though.

**Comment by GodNero** [comment]
Ambidextrous and MFFS were not added
