### ISSUE TITLE
EZStorage crafting crash

### ISSUE THREAD

**Issue by Aaronmessina** [Resonant-Rise/ResonantRiseV4#7]
###### Mod In Question

> EZStorage
###### Link to crash log

> http://puu.sh/ngvn8/6415861ae6.txt
###### Expected behavior

> EZStorage crafting
> ###### Actual Behavior
> 
> EZStorage not showing items in crafting grid, but they are actually there
###### Steps to reproduce

> Randomly happens when shift clicking recipies in from JEI, pretty often
###### Suggestion on how to fix or supply fix

> Report to mod author?

**Comment by Esriel123** [comment]
I have seen this aswell, and I notived it only happens, if you don't  clear the Grid after you used it once. It sometimes keeps invisible items in the Grid.
