### ISSUE TITLE
QoL add-ons, fixes, and updates.

### ISSUE THREAD

**Issue by GodNero** [Resonant-Rise/ResonantRiseV4#71]
Dear @misterfixit it would be super awesome if you could include/update the following mods before your next update:

Storage Drawers Extras:
https://minecraft.curseforge.com/projects/storage-drawers-extras

Bed Bugs:
https://minecraft.curseforge.com/projects/bed-bugs
(@elucent - Fixes the 1.10.2 vanilla bed bug where players can become trapped in beds.)

Also Update CharSet if you can:
http://charset.asie.pl/index.html

**Comment by GodNero** [comment]
Addendum we should update GoG3 to 1.4.7 as there is a internal name change on all items, we should get that fixed sooner rather than later:
https://github.com/DoctorWiggles/GrimoireOfGaia/releases/tag/1.4.0-ALPHA

**Comment by misterfixit** [comment]
Everything added except for charset was causing a crash with malissis core, will review later.
