### ISSUE TITLE
Crash during bootup.

### ISSUE THREAD

**Issue by ghost** [Resonant-Rise/ResonantRiseV4#74]
###### Mod In Question
> Refined Storage

###### Expected behavior
> Loads, makes it to main screen.

###### Actual Behavior
> Crashes when trying to load the model for one of the refined storage blocks.

###### Steps to reproduce
> Load up ResonantRise, wait for it to load models.

**Comment by misterfixit** [comment]
Need crash report and client logs

**Comment by ghost** [comment]
[crash-2016-12-30_11.06.15-client.txt](https://github.com/Resonant-Rise/ResonantRiseV4/files/678985/crash-2016-12-30_11.06.15-client.txt)
I have the crash report, but where do I find the client log?

**Comment by misterfixit** [comment]
Client log will be in the logs folder under fml client latest

**Comment by misterfixit** [comment]
You ran out of memory I suggest allocating at least 3gb of RAM

**Comment by ghost** [comment]
I will try with 3072 mb. If it does not work, then idk what to do, since that is pretty much the max I can do. I had 2560 before.

**Comment by misterfixit** [comment]
What is the total amount of RAM you have available?

**Comment by ghost** [comment]
It worked.
