### ISSUE TITLE
Forge Hammer cannot make iron plates IC2

### ISSUE THREAD

**Issue by moordoom** [Resonant-Rise/ResonantRiseV4#76]
###### Mod In Question
Industrial Craft 2

###### Link to crash log
no crash, just not an option

###### Expected behavior
Make Forge Hammer, go to crafting table with iron ingots and hammer, place hammer and iron ingot in in crafting table. craft.

###### Actual Behavior
When trying to make, its not an option, have to use Metal press from immersive engineering but you need copper and iron plates to make the multiblock, or Tinker's Construct but cannot make an iron plate to make a pattern, Blocking cutting machine from IC2 makes them, but you need iron plates to make a basic machine casing. They can be made with Embers Stamper, but requires a whole lists of items and machines just to get to the stamper.

###### Steps to reproduce
Make Forge Hammer, go to crafting table with iron ingots and hammer, place hammer and iron ingot in in crafting table

###### Suggestion on how to fix or supply fix
Not sure. I think the recipe may be disabled.

**Comment by Brenneman** [comment]
Same issue here.
