### ISSUE TITLE
Adding Mods

### ISSUE THREAD

**Issue by Tenkomanker** [Resonant-Rise/ResonantRiseV4#77]
First, I'd like to apologize for adding mods without permission, but I'm just trying to add more to the pack. I've been adding mods like Divine RPG and Advent of Ascension. DRPG works fine with no errors and I can play fine, but Advent of Ascension doesn't. Both DRPG and AoA were made by the same author with the other mod in mind, so AoA was made to compliment and add on to DRPG. I've seen that RR lacks in adventure compared to the experience and building aspect, so I'm adding these to add to the adventure and difficulty. Like I said, DRPG works fine and all items/mobs/bloks work in game. AoA used to have an enchantment id conflict with another mod I added, Ars Magica, so I fixed it. But now, if I launch RR it causes XReliquery to crash. Here's the crash log
> [crash-2017-03-16_12.36.12-client.txt](https://github.com/Resonant-Rise/ResonantRiseV4/files/848533/crash-2017-03-16_12.36.12-client.txt)

Any help would be appreciated. I'm looking for any solution to allow me to play with AoA, but if there are none I'm content with playing without because I still have DRPG. Thanks.

**Comment by misterfixit** [comment]
Due to the overwhelming size of that mod it will not work by simply adding
it to RR3, you will have to make your own pack for that mod

**Comment by Tenkomanker** [comment]
Oh? Well thanks for the clear up. I'll continue to play w/o AoA then. After I saw the comment I thought maybe it was because DRPG was installed too but no luck :/ I'll try to get it working on my own mod pack using the RR mods so thanks!
