### ISSUE TITLE
Blood Magic Living Armor exceeding maximum upgrade points

### ISSUE THREAD

**Issue by Dr-Excalibur** [Resonant-Rise/ResonantRiseV4#9]
###### Mod In Question

> Blood Magic
###### Link to crash log

> Not Applicable
###### Expected behavior

> As the player wears the armor, the armor notices the activities the player does, such as running, fighting, and mining. The armor assigns upgrade points based on these activities, until a threshold is reached. The threshold can be tripled by using the Ritual of Living Evolution, allowing players to get more powerful buffs.
###### Actual Behavior

> The armor occasionally ignores the threshold, causing the upgrade points earned over time to cause the player to become more powerful than they should. The greatest number of points observed at the first threshold was 115, which is over the 100 threshold. The second threshold more than triples the overage, with the greatest point overage observed being by 85 points.
###### Steps to reproduce

> Wear Living Armor through a play-through.
###### Suggestion on how to fix or supply fix

> Notify Way

**Comment by Ryahn** [comment]
Once we get a new version of BloodMagic, this will be resolved.
